name: relay-dev

services:
  # Expo Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: relay-frontend
    ports:
      - '3000:8081'
    volumes:
      - .:/frontend
      - /frontend/node_modules
  # C++ Backend
  backend:
    container_name: relay-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/backend
    ports:
      - '8080:8080'
    networks:
      - relay-network

networks:
  relay-network:
    driver: bridge
