name: relay-dev

services:
  # Next Frontend
  frontend:
    container_name: relay-frontend
    image: node:latest
    restart: unless-stopped
    command: bash -c "npm start"
    working_dir: /usr/src/app
    ports:
      - "3000:8081"
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - relay-network
    env_file:
      - ./frontend/.env.local
  # C++ Backend
  # backend:
  #   container_name: relay-backend
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./:/home/dev
  #   networks:
  #     - relay-network

networks:
  relay-network:
    driver: bridge
